### ISSUE TITLE
could I intergate this into qiankun micro-fontend project

### ISSUE THREAD

**Issue by zengyunchun** [single-spa/single-spa-angularjs#40]
I just want to use angularjs 1* on qiankun project, thanks a lot 
qiankun git url: https://github.com/umijs/qiankun

**Comment by joeldenning** [comment]
Hi @zengyunchun -  yes you can use single-spa-angularjs + qiankun together.

qiankun uses single-spa and can use single-spa-angularjs to create [single-spa applications](https://zh-hans.single-spa.js.org/docs/building-applications). [Here is an example of using single-spa-angularjs](https://github.com/joeldenning/single-spa-es5-angularjs). You would do that but insert it into the [main file for a qiankun application](https://github.com/umijs/qiankun/blob/master/examples/react16/src/index.js).

I believe that is all that is needed. I do not maintain qiankun and am not as familiar with it as I am with single-spa itself. However, the thing to keep in mind is that **a single-spa application is just an object** and that single-spa-angularjs helps you create that object.

I'm closing this issue since there is no bug here with single-spa-angularjs. However, feel free to comment further or reopen.
