### ISSUE TITLE
how to bundle qiankun to compatible es5 angularjs app like signle-spa-angular1

### ISSUE THREAD

**Issue by zengyunchun** [single-spa/single-spa-angularjs#43]
hello, I notice [qiankun](https://github.com/umijs/qiankun) micro fontend is based on single-spa, but qiankun could not integrate old ES5 Angularjs app, i want to bundle the qiankun es6 module to a script tag like your single-spa-angular1 and used by a global variable, can you teach me how to do this, thanks a lot!!

**Comment by filoxo** [comment]
The documentation for single-spa-angularjs is likely your best bet for info. Your mileage may vary. 

https://single-spa.js.org/docs/ecosystem-angularjs

**Comment by zengyunchun** [comment]
> The documentation for single-spa-angularjs is likely your best bet for info. Your mileage may vary.
> https://single-spa.js.org/docs/ecosystem-angularjs

@filoxo yeah, the document shows how to use the signleSpaAngularJS, but i want to know how to generate singleSpaAngularjs script (https://unpkg.com/single-spa-angular1@2.7.0/lib/single-spa-angular1.js)，which can use through global variable

**Comment by joeldenning** [comment]
> i want to bundle the qiankun es6 module to a script tag like your single-spa-angular1 and used by a global variable, can you teach me how to do this, thanks a lot!!

To clarify, you want to use qiankun like the following?

```html
<script src="/qiankun.js"></script>
<script>
  window.qiankun.doThings()
</script>
```

^ This is not something that qiankun currently supports. See https://unpkg.com/qiankun/ - there is an ESM (import/export) version of qiankun and a CommonJS (require/module.exports) version. Neither of those works in the browser as a global variable.

The reason that single-spa-angularjs works as a global variable is because it is compiled to Universal Module Format (UMD). If you want to commpile qiankun yourself to that format, you could do so with rollup. Here's an [example repo](https://github.com/esm-bundle/autopublish-template) of compiling a different project to a new format.

However, I'm not sure I'd recommend you do this - instead it might be better to work with the qiankun team to see if they could add a UMD bundle to their published library. @kuitos and @deterium are two maintainers of webpack - to talk with them I think it would be best if you open an issue on the qiankun repo.

**Comment by zengyunchun** [comment]
@joeldenning , Thanks for your answer in details, I have compiled to umd module and used on my projecet .
