### ISSUE TITLE
Non-parcel bundles require registering the module

### ISSUE THREAD

**Issue by huwshimi** [single-spa/single-spa-angularjs#56]
When upgrading to 4.2.0 I discovered I needed to manually register the module with `angular.module("single-spa-angularjs", []);` otherwise I got a bootstrapping error from single-spa.

I couldn't find anything in the docs except for a few clues in the parcel sections. There might be a better fix, my knowledge of AngularJS is limited.

I've reproduced the error here: https://codepen.io/huwshimi/pen/OJbPEZV

If you look in you browser console you'll see the error, and uncommenting the first line should make the error go away.

When using a parcel the module is registered when you import the parcel directive:

https://github.com/single-spa/single-spa-angularjs/pull/55/files#diff-660ba0e334878cc4c40deb046d413bf056dbde6a35edec191ed23fdc3022cceaR3

**Comment by sparkiegeek** [comment]
#46

**Comment by joeldenning** [comment]
Thanks for the clear description - I had intended the code to be defensive about this, but didn't realize that calling `angular.module('single-spa-angularjs')` would throw an error instead of returning null. I've fixed it in #57 and released the fix in https://github.com/single-spa/single-spa-angularjs/releases/tag/v4.2.1

**Comment by huwshimi** [comment]
Thanks @joeldenning! That fix works perfectly for us.
